-- Add AI correction field to challenges
ALTER TABLE public.challenges
ADD COLUMN IF NOT EXISTS ai_correction_enabled BOOLEAN DEFAULT false;

-- Add is_ai_review field to reviews to identify AI-generated reviews
ALTER TABLE public.reviews
ADD COLUMN IF NOT EXISTS is_ai_review BOOLEAN DEFAULT false;

-- Comment for documentation
COMMENT ON COLUMN public.challenges.ai_correction_enabled IS 'When enabled, submissions to this challenge will be automatically reviewed by AI';
COMMENT ON COLUMN public.reviews.is_ai_review IS 'Indicates if this review was generated by AI';
